### ISSUE TITLE
Crash, when content-type not provided

### ISSUE THREAD

**Issue by car1ot** [DimaCrafter/dc-api-core#13]
```
TypeError: Cannot read property 'split' of undefined
    at /root/plinko.cash/backend/node_modules/dc-api-core/index.js:69:54
```

Fix 68 row to:
`if (body.length === 0 || !req.headers['content-type']) return resolve();`

**Comment by mayerdev** [comment]
You can create pull request.

**Comment by car1ot** [comment]
> 
> 
> You can create pull request.

It seems that the creator does not care.

**Comment by car1ot** [comment]
Unsupported package. Use on your own risk.

**Comment by mayerdev** [comment]
> It seems that the creator does not care.

This is an open source bro :D

**Comment by car1ot** [comment]
> 
> 
> > It seems that the creator does not care.
> 
> This is an open source bro :D

Okay, but used by people open-source projects must me supported by developer. Anyway, pull requests with serious fixes should be accepted.
