### ISSUE TITLE
Global error handling

### ISSUE THREAD

**Issue by car1ot** [DimaCrafter/dc-api-core#15]
I need to collect `500` errors data. What is the best way to access the error handler globally so as not to make try catch blocks in every request on the controller? P.S. in each request error callback, I need to execute the `Sentry.captureException(err)` for logging errors by a third-party service.

**Comment by DimaCrafter** [comment]
Added in dc-api-core v0.2.4-1.

startup.js:

```
const { onError } = require('dc-api-core');
onError(info => console.log(info));
```

controllers/Test.js
```
module.exports = class Test {
    error () { throw new Error('Some unexpected error!'); }
}
```

Console output:

```
{
    isSystem: false,
    controller: 'Test',
    action: 'error',
    message: 'Some unexpected error!',
    error: <Error object>
}
```
